default:
    image: node
stages: 
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - node --version
        - yarn --version
        - npm --version
    rules:
    # Run on Merge requests
    - if: $CI_MERGE_REQUEST_IID    

    
